[node]
id = "ffffffff-ffff-ffff-ffff-ffffffffffff"

[logging]

[logging.all_logger]
default_level = "info"
default_name = "root"

[[logging.file_appenders]]
logger_names = ["root"]
enable = true
write_level = "debug"
file_max_size = 100_000_000
file_max_count = 3
file_name = "beaver.log"

[logging.console_appender]
logger_names = ["root"]
enable = true
write_level = "info"
